export const TRIGGER_ANIMATION='TRIGGER_ANIMATION';
export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_ITEMS='GET_CART_ITEMS';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';
export const PROCEED_TO_CHECKOUT = 'PROCEED_TO_CHECKOUT';
export const CART_PURCHASED = 'CART_PURCHASED';