export const SELECTED_ITEM='SELECTED_ITEM';
export const LOAD_ITEMS='LOAD_ITEMS';
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const SET_LOADING_FALSE ='SET_LOADING_FALSE';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_SEARCH = 'SET_SEARCH';
export const RESET_SEARCH = 'RESET_SEARCH';