export const USER_REQUEST='USER_REQUEST';
export const USER_SUCCSES = 'USER_SUCCSES';
export const USER_ERROR = 'USER_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT'
export const CHECK_BALANCE = 'CHECK_BALANCE';
export const MAKE_A_TRANSACTION = 'MAKE_A_TRANSACTION';